GET https://vast-springs-99063.herokuapp.com/api/flowers

###
POST https://vast-springs-99063.herokuapp.com/api/flowers
Content-Type: application/json

{
  "sepalLength": 100,
  "color": 1,
  "price": 100
}